# Generated by Django 3.0.4 on 2020-12-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hezongyy_py1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('xq', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hezongyy_py',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='longyi_tjzq1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('xq', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'longyi_tjzq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='longyi_yp1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('xq', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'longyi_yp',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scjuchuang_py1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('xq', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
                ('price3', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scjuchuang_py',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='scytyy_ypzq1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('xq', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'scytyy_ypzq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ypzdw_jtj1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('sj', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ypzdw_jtj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ysb_lyg1',
            fields=[
                ('ID', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cj', models.CharField(max_length=100)),
                ('gg', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ysb_lyg',
                'managed': True,
            },
        ),
    ]
