# Generated by Django 3.0.4 on 2021-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20201230_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBA_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qy', models.CharField(max_length=32)),
                ('ccrq', models.CharField(max_length=32)),
                ('df', models.IntegerField()),
                ('zg', models.IntegerField()),
                ('lb', models.IntegerField()),
            ],
        ),
    ]
